Add scripts to automate upload
mestery/thenetlol pull request #21
Opened 2021-01-29 18:42 UTC by dave-tucker

Once video is edited, it should be as easy as documented in the README

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

2021-01-30 18:57 UTC, mestery requested changes
I think we should remove the `scripts/ep6.json` file, otherwise this is good!

2021-01-30 18:57 UTC, mestery commented on scripts/ep6.json
> +{
I don't think we want this file merged in, can you remove confirm and remove it if so?

2021-01-31 18:07 UTC, mestery approved these changes

2021-03-29 19:06 UTC, mestery commented
@dave-tucker  this is fine to me, if you agree, either merge it or let me know and I will merge it! Thanks!

2021-03-29 19:10 UTC, dave-tucker commented
Yeah let's merge it. I thought we could check in the episode yaml files. Why not? At least if we ever need to re-upload an episode the file is there 😉

2021-03-29 19:12 UTC, merged